version: '3.8'
services:
  db:
    container_name: harkka-db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harkka_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: